#-------------------------------------------------------------------------------
# Carbon Dark
#-------------------------------------------------------------------------------


colors:
#-------------------------------------------------------------------------------

  # Special
  debug: &debug "#ff00ff"

  # Primary (16-31)
  primary_0: &primary_0 "#000610"
  primary_1: &primary_1 "#000d1e"
  primary_2: &primary_2 "#00152d"
  primary_3: &primary_3 "#011d3c"
  primary_4: &primary_4 "#01244b"
  primary_5: &primary_5 "#022c5a"
  primary_6: &primary_6 "#023469"
  primary_7: &primary_7 "#023b78"
  primary_8: &primary_8 "#034387"
  primary_9: &primary_9 "#034b96"
  primary_10: &primary_10 "#055eb5"
  primary_11: &primary_11 "#056dc4"
  primary_12: &primary_12 "#057cd3"
  primary_13: &primary_13 "#058be1"
  primary_14: &primary_14 "#059af0"
  primary_15: &primary_15 "#05aaff"

  # Secondary (32-47)
  secondary_0: &secondary_0 "#000e14"
  secondary_1: &secondary_1 "#02151d"
  secondary_2: &secondary_2 "#041d27"
  secondary_3: &secondary_3 "#062431"
  secondary_4: &secondary_4 "#082c3b"
  secondary_5: &secondary_5 "#0a3344"
  secondary_6: &secondary_6 "#0c3b4e"
  secondary_7: &secondary_7 "#0e4e65"
  secondary_8: &secondary_8 "#0d5d74"
  secondary_9: &secondary_9 "#0c6c84"
  secondary_10: &secondary_10 "#0b7b93"
  secondary_11: &secondary_11 "#0a8aa2"
  secondary_12: &secondary_12 "#0999b1"
  secondary_13: &secondary_13 "#08a8c0"
  secondary_14: &secondary_14 "#07b7cf"
  secondary_15: &secondary_15 "#06c6df"

  # Text (48-63)
  text_0: &text_0 "#001020"
  text_1: &text_1 "#0e1e2e"
  text_2: &text_2 "#1d2d3d"
  text_3: &text_3 "#2c3c4c"
  text_4: &text_4 "#3b4b5b"
  text_5: &text_5 "#4a5a6a"
  text_6: &text_6 "#596979"
  text_7: &text_7 "#687888"
  text_8: &text_8 "#768696"
  text_9: &text_9 "#8595a5"
  text_10: &text_10 "#94a4b4"
  text_11: &text_11 "#a3b3c3"
  text_12: &text_12 "#b2c2d2"
  text_13: &text_13 "#c1d1e1"
  text_14: &text_14 "#d0e0f0"
  text_15: &text_15 "#dfefff"

  # Gray (64-79)
  gray_0: &gray_0 "#0b0b0e"
  gray_1: &gray_1 "#191a20"
  gray_2: &gray_2 "#282932"
  gray_3: &gray_3 "#363844"
  gray_4: &gray_4 "#454757"
  gray_5: &gray_5 "#535669"
  gray_6: &gray_6 "#62657b"
  gray_7: &gray_7 "#71758e"
  gray_8: &gray_8 "#71758e"
  gray_9: &gray_9 "#83869c"
  gray_10: &gray_10 "#9598ab"
  gray_11: &gray_11 "#a7aab9"
  gray_12: &gray_12 "#babbc8"
  gray_13: &gray_13 "#cccdd6"
  gray_14: &gray_14 "#dedfe5"
  gray_15: &gray_15 "#f1f1f4"

  # Red (80-89)
  red_0: &red_0 "#1a0200"
  red_1: &red_1 "#4d0500"
  red_2: &red_2 "#800900"
  red_3: &red_3 "#b30c00"
  red_4: &red_4 "#cc0e00"
  red_5: &red_5 "#e60f00"
  red_6: &red_6 "#ff291a"
  red_7: &red_7 "#ff584d"
  red_8: &red_8 "#ff8880"
  red_9: &red_9 "#ffb8b3"

  # Orange (90-99)
  orange_0: &orange_0 "#1a0f00"
  orange_1: &orange_1 "#331f00"
  orange_2: &orange_2 "#663d00"
  orange_3: &orange_3 "#995c00"
  orange_4: &orange_4 "#ff9500"
  orange_5: &orange_5 "#ff9900"
  orange_6: &orange_6 "#ffad33"
  orange_7: &orange_7 "#ffc266"
  orange_8: &orange_8 "#ffd699"
  orange_9: &orange_9 "#ffebcc"

  # Yellow (100-109)
  yellow_0: &yellow_0 "#332a00"
  yellow_1: &yellow_1 "#665300"
  yellow_2: &yellow_2 "#997d00"
  yellow_3: &yellow_3 "#cca700"
  yellow_4: &yellow_4 "#ffd000"
  yellow_5: &yellow_5 "#ffda33"
  yellow_6: &yellow_6 "#ffde4d"
  yellow_7: &yellow_7 "#ffe880"
  yellow_8: &yellow_8 "#fff1b3"
  yellow_9: &yellow_9 "#fffae6"

  # Green (110-119)
  green_0: &green_0 "#001a0f"
  green_1: &green_1 "#00331f"
  green_2: &green_2 "#00663d"
  green_3: &green_3 "#00995c"
  green_4: &green_4 "#00cc7a"
  green_5: &green_5 "#00e68a"
  green_6: &green_6 "#1affa3"
  green_7: &green_7 "#4dffb8"
  green_8: &green_8 "#80ffcc"
  green_9: &green_9 "#b3ffe0"

  # Cyan (120-129)
  cyan_0: &cyan_0 "#00131a"
  cyan_1: &cyan_1 "#00384d"
  cyan_2: &cyan_2 "#005e80"
  cyan_3: &cyan_3 "#0083b3"
  cyan_4: &cyan_4 "#00a8e6"
  cyan_5: &cyan_5 "#00bbff"
  cyan_6: &cyan_6 "#33c9ff"
  cyan_7: &cyan_7 "#66d6ff"
  cyan_8: &cyan_8 "#99e4ff"
  cyan_9: &cyan_9 "#ccf1ff"

  # Blue (130-139)
  blue_0: &blue_0 "#00061a"
  blue_1: &blue_1 "#000d33"
  blue_2: &blue_2 "#001a66"
  blue_3: &blue_3 "#002699"
  blue_4: &blue_4 "#0033cc"
  blue_5: &blue_5 "#003fff"
  blue_6: &blue_6 "#3366ff"
  blue_7: &blue_7 "#668cff"
  blue_8: &blue_8 "#99b3ff"
  blue_9: &blue_9 "#ccd9ff"

  # Purple (140-149)
  purple_0: &purple_0 "#0e001a"
  purple_1: &purple_1 "#1d0033"
  purple_2: &purple_2 "#3a0066"
  purple_3: &purple_3 "#570099"
  purple_4: &purple_4 "#7400cc"
  purple_5: &purple_5 "#9200ff"
  purple_6: &purple_6 "#a733ff"
  purple_7: &purple_7 "#bd66ff"
  purple_8: &purple_8 "#d399ff"
  purple_9: &purple_9 "#e9ccff"

  # Magenta (150-159)
  magenta_0: &magenta_0 "#1a000a"
  magenta_1: &magenta_1 "#330014"
  magenta_2: &magenta_2 "#660029"
  magenta_3: &magenta_3 "#99003d"
  magenta_4: &magenta_4 "#cc0052"
  magenta_5: &magenta_5 "#ff0066"
  magenta_6: &magenta_6 "#ff3385"
  magenta_7: &magenta_7 "#ff66a3"
  magenta_8: &magenta_8 "#ff99c2"
  magenta_9: &magenta_9 "#ffcce0"

  # ANSI named shortcuts
  ansi_black: *gray_0
  ansi_red: *red_4
  ansi_green: *green_3
  ansi_yellow: *orange_6
  ansi_blue: *primary_10
  ansi_magenta: *magenta_4
  ansi_cyan: *secondary_10
  ansi_white: *text_13
  ansi_brblack: *text_8
  ansi_brred: *red_6
  ansi_brgreen: *green_5
  ansi_bryellow: *yellow_6
  ansi_brblue: *primary_15
  ansi_brmagenta: *magenta_6
  ansi_brcyan: *secondary_15
  ansi_brwhite: *text_15

  # Themed
  system_bg: *gray_0
  system_text: *text_13

  terminal_bg: *gray_0
  terminal_text: *text_13

  editor_bg: *gray_0
  editor_text_normal: *secondary_9


fonts:
#-------------------------------------------------------------------------------

  mono: "Iosevka NF"
  sans: "Calibri"
  serif: "Georgia"